### ISSUE TITLE
Skip Options when they are close

### ISSUE THREAD

**Issue by tetenpapier** [poletaevvlad/cmdparse#2]
I don't know if it's possible but when I've a struct with 2 fields Options, I can't pass the second without the first : 

```rust
enum Enum {
    Foo,
    Bar,
}

struct Command {
    i: usize,
    bar: Option<u32>,
    foo: Option<Enum>,
}
```

Here, `0 0` pass but not `0 foo`. I must type `0 0 foo`.

Maybe the crate can ignore one argument when two options of different types are next to each other ?

**Comment by poletaevvlad** [comment]
That's a bit tricky, but should be possible to do with a custom parser. I don't think it's a good idea to make this the default behavior as may be confusing which types are compatible with each other.

Essentially, for parsing, you could try to parse the type, and on success to return it, otherwise return the type's `Defailt::default()`.

For complition, you still would need to parse the type, as the completion algorithm consumes tokens without validation and in general doesn't know how many tokens to consume. 

My idea is:

- Run completion on the type, remember the suggestions;
- If the last token consumed was final, return the suggestions + the original token stream and a flag that's the value has been consumed;
- If not, parse the type:
  - on success, return the completion result;
  - on failure, return the original token stream with a value consumption flag set.

There may be some cases that I've missed here, I'd need to experiment with it when I have time to be sure.

**Comment by tetenpapier** [comment]
Ok, thank you for your answer and your idea ! I'll try to make my own parser with that behavior.
